import { describe, it, expect } from "vitest";
import type { CategoryName } from "@prisma/client";
import { tagCategory } from "../lib/normalization/categoryTagger";
import { categorize } from "../lib/normalization/categorize";
import { classifyBySimilarity } from "../lib/normalization/semanticCategorizer";

/**
 * TAIL EVAL SET — hand-labeled merchants the regex rules DO NOT cover.
 *
 * Methodology note (important): labels here are hand-assigned, NOT generated by
 * the rule tagger. Each case is asserted to be a genuine rule-miss first
 * (tagCategory → OTHER), so "before/after" measures real accuracy on the tail,
 * not agreement with the rules. If a case ever becomes a rule hit, the guard
 * assertion fails and forces us to pick a truer tail example.
 */
const TAIL_CASES: Array<{ merchant: string; expected: CategoryName }> = [
  { merchant: "OVEN STORY",           expected: "FOOD_DINING" },
  { merchant: "HALDIRAM NAGPUR",      expected: "FOOD_DINING" },
  { merchant: "BIKANERVALA OUTLET",   expected: "FOOD_DINING" },
  { merchant: "LICIOUS",              expected: "GROCERIES" },
  { merchant: "COUNTRY DELIGHT",      expected: "GROCERIES" },
  { merchant: "MILKBASKET",           expected: "GROCERIES" },
  { merchant: "CHAAYOS",              expected: "COFFEE_CAFES" },
  { merchant: "NAMMA YATRI",          expected: "TRANSPORT" },
  { merchant: "BLUSMART MOBILITY",    expected: "TRANSPORT" },
  { merchant: "NAYARA ENERGY",        expected: "TRANSPORT" },
  { merchant: "CROMA",                expected: "SHOPPING" },
  { merchant: "DECATHLON",            expected: "SHOPPING" },
  { merchant: "LENSKART",             expected: "SHOPPING" },
  { merchant: "WELLNESS FOREVER",     expected: "HEALTHCARE" },
  { merchant: "LAL PATHLABS",         expected: "HEALTHCARE" },
  { merchant: "TATA POWER",           expected: "UTILITIES" },
  { merchant: "WONDERLA",             expected: "ENTERTAINMENT" },
  { merchant: "SONY LIV",             expected: "SUBSCRIPTIONS" },
  { merchant: "INDMONEY",             expected: "INVESTMENTS" },
  { merchant: "PHYSICS WALLAH",       expected: "EDUCATION" },
];

describe("tail eval — every case is a genuine rule miss", () => {
  for (const { merchant } of TAIL_CASES) {
    it(`rules alone return OTHER for "${merchant}"`, () => {
      expect(tagCategory(merchant, merchant)).toBe("OTHER");
    });
  }
});

describe("cascade recovers the long tail via similarity", () => {
  for (const { merchant, expected } of TAIL_CASES) {
    it(`categorizes "${merchant}" → ${expected}`, () => {
      const { category, source } = categorize(merchant, merchant);
      expect(category).toBe(expected);
      expect(source).toBe("similarity");
    });
  }
});

describe("before/after coverage on the tail", () => {
  it("rules cover ~0% but the cascade covers the large majority", () => {
    const ruleHits = TAIL_CASES.filter((c) => tagCategory(c.merchant) !== "OTHER").length;
    const cascadeCorrect = TAIL_CASES.filter(
      (c) => categorize(c.merchant, c.merchant).category === c.expected,
    ).length;

    const before = ruleHits / TAIL_CASES.length;
    const after = cascadeCorrect / TAIL_CASES.length;

    // eslint-disable-next-line no-console
    console.log(`Tail coverage — rules: ${Math.round(before * 100)}%  →  cascade: ${Math.round(after * 100)}%`);

    expect(before).toBe(0);
    expect(after).toBeGreaterThanOrEqual(0.85);
  });
});

describe("similarity classifier rejects unrelated strings", () => {
  it("returns null for gibberish rather than forcing a category", () => {
    expect(classifyBySimilarity("XZQWKPLM VOID 99")).toBeNull();
  });
  it("returns null for empty / too-short input", () => {
    expect(classifyBySimilarity("")).toBeNull();
    expect(classifyBySimilarity("A")).toBeNull();
  });
});
